require 'pry'
require 'net/http'
require 'open-uri'
require 'json'
require 'dotenv/load'
require 'awesome_print'
require 'tty-prompt'
require 'colorize'

require_relative '../lib/modules/freshies'
require_relative '../lib/api'
require_relative '../lib/current'
require_relative '../lib/future'
require_relative '../lib/cli'
